---
title: Daftar Ulang Calon Mahasiswa Baru Peserta KIP-Kuliah Jalur SBMPTN 2022
author: kemahasiswaan
date: '2022-03-28'
slug: []
categories:
  - ''
tags:
  - KIP-K
  - KIP-K 2022
description: ''
thumbnail: ''
---

#### (Diumumkan oleh Kemahasiswaan -- BAKP)

1.  Wajib melakukan daftar ulang Calon Mahasiswa Baru jalur **UTBK-SBMPTN**, **Tgl 23 s.d. 30 Juni 2022** pada Laman : [**https://admisi.untirta.ac.id**](https://admisi.untirta.ac.id){.uri target="_blank"}

    > **Selesaikan dahulu proses registrasi ulang admisi** sebelum daftar ulang di laman ini.

2.  Lengkapi data pada laman [**https://kip-kuliah.kemdikbud.go.id**](https://kip-kuliah.kemdikbud.go.id){.uri target="_blank"}

    Lengkapi dan perbaharui semua data yang dicantumkan di laman tersebut. Contoh: alamat, nomor HP, prestasi, upload foto keluarga, foto rumah (tampak ruang keluarga)

3.  Tanggal **23 s.d. 30 Juni 2022** wajib melakukan daftar ulang Calon Mahasiswa Baru KIP Kuliah pada link [**https://link.untirta.ac.id/KIPK22**](https://link.untirta.ac.id/KIPK22){target="_blank"} serta mengupload file berukuran **tidak lebih dari 1 MB** dengan format nama file (rename): **No.SBMPTN_Nama Camaba_Jenis Data**.

    ```{=html}
    <style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;}
    .tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
      overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
      font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
    .tg .tg-9wq8{border-color:inherit;text-align:center;vertical-align:middle}
    .tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
    </style>
    <table class="tg">
    <thead>
      <tr>
        <th class="tg-9wq8">No</th>
        <th class="tg-9wq8">File yang harus diunggah</th>
        <th class="tg-9wq8">Jenis File</th>
        <th class="tg-9wq8">Contoh Nama File<br>(No.SNMPTN_Nama Camaba_Jenis data)<br></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="tg-0pky">a.</td>
        <td class="tg-0pky">Kartu Tanda Penduduk (KTP)   </td>
        <td class="tg-0pky">PDF/JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_KTP   </td>
      </tr>
      <tr>
        <td class="tg-0pky">b.</td>
        <td class="tg-0pky">Kartu Keluarga (KK)   </td>
        <td class="tg-0pky">PDF/JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_KK   </td>
      </tr>
      <tr>
        <td class="tg-0pky">c.</td>
        <td class="tg-0pky">Rekening Listrik (Bulan Terakhir)   </td>
        <td class="tg-0pky">PDF/JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Listrik   </td>
      </tr>
      <tr>
        <td class="tg-0pky">d.</td>
        <td class="tg-0pky">Slip Gaji / Surat Keterangan Penghasilan Ayah   </td>
        <td class="tg-0pky">PDF/JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Ayah   </td>
      </tr>
      <tr>
        <td class="tg-0pky">e.</td>
        <td class="tg-0pky">Slip Gaji / Surat Keterangan Penghasilan Ibu   </td>
        <td class="tg-0pky">PDF/JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Ibu   </td>
      </tr>
      <tr>
        <td class="tg-0pky">f.</td>
        <td class="tg-0pky">Foto/Scan Gaji / Surat Keterangan Penghasilan Wali   </td>
        <td class="tg-0pky">PDF/JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Wali   </td>
      </tr>
      <tr>
        <td class="tg-0pky">g.</td>
        <td class="tg-0pky">Foto/Scan Kartu Indonesia Pintar (KIP) / Kartu Keluarga Sejahtera (KKS) / Program Keluarga Harapan (PKH) / Surat DTKS / SKTM (boleh lebih dari 1)   </td>
        <td class="tg-0pky">PDF/JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_KIP<br>1234567890_Budi Pratama_KKS<br>1234567890_Budi Pratama_PKH<br>1234567890_Budi Pratama_DTKS<br>1234567890_Budi Pratama_SKTM   </td>
      </tr>
      <tr>
        <td class="tg-0pky">h.</td>
        <td class="tg-0pky">Foto Rumah Tinggal Tampak Depan   </td>
        <td class="tg-0pky">JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Depan   </td>
      </tr>
      <tr>
        <td class="tg-0pky">i.</td>
        <td class="tg-0pky">Foto Rumah Tampak Belakang   </td>
        <td class="tg-0pky">JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Belakang   </td>
      </tr>
      <tr>
        <td class="tg-0pky">j.</td>
        <td class="tg-0pky">Foto Ruang Keluarga   </td>
        <td class="tg-0pky">JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Keluarga   </td>
      </tr>
      <tr>
        <td class="tg-0pky">k.</td>
        <td class="tg-0pky">Foto Ruang Dapur   </td>
        <td class="tg-0pky">JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Dapur   </td>
      </tr>
      <tr>
        <td class="tg-0pky">l.</td>
        <td class="tg-0pky">Foto Kamar Mandi   </td>
        <td class="tg-0pky">JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Mandi   </td>
      </tr>
      <tr>
        <td class="tg-0pky">m.</td>
        <td class="tg-0pky">Rute Perjalanan dari pusat kota/kabupaten ke rumah tinggal, berupa tempat-tempat yang dapat dijadikan patokan   </td>
        <td class="tg-0pky">PDF/JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Rute   </td>
      </tr>
      <tr>
        <td class="tg-0pky">n.<br></td>
        <td class="tg-0pky">Foto/Scan SPPT PBB   </td>
        <td class="tg-0pky">PDF/JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_PBB</td>
      </tr>
      <tr>
        <td class="tg-0pky">o.</td>
        <td class="tg-0pky">Form Surat Pernyataan KIP Kuliah, dapat didownload di link <a href="http://bit.ly/PernyataanKIPK" target="_blank" rel="noopener noreferrer">http://bit.ly/PernyataanKIPK</a>    </td>
        <td class="tg-0pky">PDF/JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Surat   </td>
      </tr>
      <tr>
        <td class="tg-0pky">p.</td>
        <td class="tg-0pky">Sertifikat/Piagam penghargaan atas prestasi akademik/non-akademik yang pernah diraih di SMA/SMK/MA/sederajat   </td>
        <td class="tg-0pky">PDF/JPG   </td>
        <td class="tg-0pky">1234567890_Budi Pratama_Prestasi1<br>1234567890_Budi Pratama_Prestasi2<br>1234567890_Budi Pratama_Prestasi3<br>1234567890_Budi Pratama_Prestasi4<br>1234567890_Budi Pratama_Prestasi5   </td>
      </tr>
    </tbody>
    </table>
    ```

4.  Hasil Verifikasi akan diumumkan pada **06 Juli 2022** **(pukul 16:00 Wib)** melalui web [**kemahasiswaan.untirta.ac.id**](https://kemahasiswaan.untirta.ac.id){target="_blank"}

    -   Jika **tidak diterima**, silahkan membayar UKT sesuai yang tertera di laman [**admisi.untirta.ac.id**](https://admisi.untirta.ac.id){target="_blank"}
    -   Jika **diterima**, anda tidak membayar UKT.

5.  Bergabung dengan grup Telegram : [**https://link.untirta.ac.id/TeleKIPK22**](https://link.untirta.ac.id/TeleKIPK22){target="_blank"}

6.  Hotline Kemahasiswaan BAKP [**081210275080**](https://wa.me/6281210275080){target="_blank"}
