---
title: Daftar Ulang Mahasiswa Baru Peserta KIP-Kuliah Jalur SBMPTN 2021
author: ''
date: '2021-06-14'
slug: []
categories: []
tags: []
description: ''
thumbnail: ''
---

#### (Diumumkan oleh Kemahasiswaan -- BAKP)

1.  Wajib melakukan daftar ulang Calon Mahasiswa Baru jalur SBMPTN, **Tgl 15 s.d. 25 Juni\
    2021** pada Laman : [**http://admisi.untirta.ac.id**](http://admisi.untirta.ac.id){.uri target="_blank"}

2.  Lengkapi data pada laman [**https://kip-kuliah.kemdikbud.go.id/**](https://kip-kuliah.kemdikbud.go.id/){.uri target="_blank"}

    Lengkapi dan perbaharui semua data yang dicantumkan di laman tersebut. Contoh: alamat, nomor HP, prestasi, upload foto keluarga, foto rumah (tampak ruang keluarga)

3.  Tanggal **15 s.d. 24 Juni 2021** wajib melakukan daftar ulang Calon Mahasiswa Baru KIP Kuliah pada link [**http://bit.ly/KIPK-Untirta-21**](http://bit.ly/KIPK-Untirta-21){.uri} serta mengupload file berukuran **tidak lebih dari 1 MB** dengan format nama file (rename): **No. SBMPTN_Nama Camaba_Jenis Data**.

    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | **No** | **File yang harus di upload**                                                                                                                                      | **Jenis File** | **Contoh Nama file**<br>**(No.SNMPTN_Nama Camaba_Jenis data)**                                                                                                              |
    +========+====================================================================================================================================================================+================+=============================================================================================================================================================================+
    | a\.    | Kartu Tanda Penduduk (KTP)                                                                                                                                         | PDF/JPG        | 12345678_Budi Pratama_KTP                                                                                                                                                   |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | b\.    | Kartu Keluarga (KK)                                                                                                                                                | PDF/JPG        | 12345678_Budi Pratama_KK                                                                                                                                                    |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | c\.    | Rekening Listrik (Bulan Terakhir)                                                                                                                                  | PDF/JPG        | 12345678_Budi Pratama_Listrik                                                                                                                                               |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | d\.    | Slip Gaji / Surat Keterangan Penghasilan Ayah                                                                                                                      | PDF/JPG        | 12345678_Budi Pratama_Ayah                                                                                                                                                  |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | e\.    | Slip Gaji / Surat Keterangan Penghasilan Ibu                                                                                                                       | PDF/JPG        | 12345678_Budi Pratama_Ibu                                                                                                                                                   |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | f\.    | Foto/Scan Gaji / Surat Keterangan Penghasilan Wali                                                                                                                 | PDF/JPG        | 12345678_Budi Pratama_Wali                                                                                                                                                  |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | g\.    | Foto/Scan Kartu Indonesia Pintar (KIP) / Kartu Keluarga <br> Sejahtera (KKS) / Program Keluarga Harapan (PKH) / <br>Surat DTKS / SKTM                              | PDF/JPG        | 12345678_Budi Pratama_KIP<br>12345678_Budi Pratama_KKS<br>12345678_Budi Pratama_PKH<br>12345678_Budi Pratama_DTKS<br>12345678_Budi Pratama_SKTM                             |
    |        |                                                                                                                                                                    |                |                                                                                                                                                                             |
    |        | (boleh lebih dari 1)                                                                                                                                               |                |                                                                                                                                                                             |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | h\.    | Foto Rumah Tinggal Tampak Depan                                                                                                                                    | JPG            | 12345678_Budi Pratama_Depan                                                                                                                                                 |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | i\.    | Foto Rumah Tampak Belakang                                                                                                                                         | JPG            | 12345678_Budi Pratama_Belakang                                                                                                                                              |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | j\.    | Foto Ruang Keluarga                                                                                                                                                | JPG            | 12345678_Budi Pratama_Keluarga                                                                                                                                              |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | k\.    | Foto Ruang Dapur                                                                                                                                                   | JPG            | 12345678_Budi Pratama_Dapur                                                                                                                                                 |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | l\.    | Foto Kamar Mandi                                                                                                                                                   | JPG            | 12345678_Budi Pratama_Mandi                                                                                                                                                 |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | m\.    | Rute Perjalanan dari pusat kota/kabupaten ke rumah <br>tinggal, berupa tempat-tempat yang dapat dijadikan <br>patokan                                              | PDF/JPG        | 12345678_Budi Pratama_Rute                                                                                                                                                  |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | n\.    | Foto/Scan SPPT PBB                                                                                                                                                 | PDF/JPG        | 12345678_Budi Pratama_PBB                                                                                                                                                   |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | o.     | Form Surat Pernyataan KIP Kuliah bermaterai 10.000, <br>dapat didownload di link [**http://bit.ly/PernyataanKIPK**](http://bit.ly/PernyataanKIPK){target="_blank"} | PDF/JPG        | 12345678_Budi Pratama_Surat                                                                                                                                                 |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | p.     | Sertifikat/Piagam penghargaan atas prestasi <br>akademik/non-akademik yang pernah diraih di <br>SMA/SMK/MA/sederajat                                               | PDF/JPG        | 12345678_Budi Pratama_Prestasi1<br>12345678_Budi Pratama_Prestasi2<br>12345678_Budi Pratama_Prestasi3<br>12345678_Budi Pratama_Prestasi4<br>12345678_Budi Pratama_Prestasi5 |
    +--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

4.  Hasil Verifikasi akan diumumkan pada **29 Juni 2021** melalui web [**kemahasiswaan.untirta.ac.id**](https://kemahasiswaan.untirta.ac.id)

    -   Jika **tidak diterima**, silahkan membayar UKT sesuai yang tertera di laman [**admisi.untirta.ac.id**](https://admisi.untirta.ac.id)
    -   Jika **diterima**, anda tidak membayar UKT.

5.  Bergabung dengan grup Telegram : [**http://bit.ly/KIPKUntirta2021**](http://bit.ly/KIPKUntirta2021){.uri}

6.  Hotline Kemahasiswaan BAKP 081210275080
