---
title: Bantuan UKT Kemdikbudristek Tahun 2021
author: kemahasiswaan
date: '2021-08-26'
slug: []
categories: []
tags:
  - bantuan ukt
description: ''
thumbnail: ''
---

Berdasarkan [**Pengumuman Nomor: B/1431/UN43/KM.01.00/2021**](https://drive.google.com/file/d/11cfZ60-H9bIx_0Mx81oNjW_U6cwp5vKR/view){target="_blank"} tanggal 26 Agustus 2021, mahasiswa Universitas Sultan Ageng Tirtayasa program D-3 dan S-1 dapat mengajukan permohonan bantuan pembayaran UKT kepada Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi melalui Rektor Universitas Sultan Ageng Tirtaysa dengan ketentuan berikut.

### **A.  Persyaratan**

Prioritas calon penerima bantuan UKT adalah:

1.  Mahasiswa yang orang tua/penanggung biaya kuliah mengalami kendala finansial karena terdampak pandemi Covid-19 dan mengalami kesulitan membayar UKT Semester Gasal Tahun Akademik 2021/2022.
2.  Mahasiswa berada di semester 3, 5, dan 7.
3.  Mahasiswa yang memiliki besaran UKT pada Kategori I dan II.
4.  Mahasiswa yang berasal dari wilayah 3T/wilayah terpencil.
5.  Mahasiswa Yatim

### **B.  Mekanisme Pengajuan**

Mahasiswa mengajukan permohonan kepada Rektor melalui link [**https://link.untirta.ac.id/BantuanUKT**](https://link.untirta.ac.id/BantuanUKT)dengan melampirkan dokumen pendukung sebagai berikut:

1.  Surat Permohonan Bantuan UKT (format bisa diunduh [**di sini**](https://drive.google.com/file/d/11UW8S8TNavvXkCgYCELoXg_6KXSzbBUL/view?usp=sharing){target="_blank"});
2.  Surat keterangan pekerjaan orang tua/penanggung biaya kuliah dari Kepala Desa/Lurah; atau Surat Pemutusan Hubungan Kerja (PHK) dari perusahaan/instansi orang tua/penanggung biaya bekerja, bila ada;
3.  Surat Pernyataan belum menerima beasiswa (format bisa diunduh [**di sini**](https://docs.google.com/document/d/11V8KI1V34KuNu21g5olRRs30UA6GSewg/edit?usp=sharing&ouid=108370448589641088671&rtpof=true&sd=true){target="_blank"});
4.  Scan Kartu Tanda Pengenal (KTP);
5.  Scan Kartu Keluarga (KK).;
6.  Bukti bayar UKT (jika sudah membayar UKT) dan Bukti Penangguhan UKT berupa pdf *print out* email (jika mengikuti penangguhan);
7.  Jika ayah sudah meninggal, silahkan sertakan surat keterangan kematian dan keterangan ibu belum menikah lagi (format bisa diunduh [**di sini**](https://drive.google.com/file/d/11UsiYWHSZZlzOaXm5h8ZAKXKy5H6_Lhs/view?usp=sharing){target="_blank"});
8.  Scan buku tabungan BNI;

### **C.  Jadwal Proses Permohonan**

1.  Pengajuan Permohonan: **27 Agustus s.d. 3 September 2021**
2.  Verifikasi Data: **06 -- 10 September 2021**
3.  Pengajuan daftar nama pemohon ke Puslapdik: **13 September 2021**
4.  Pengumuman diterima/ditolaknya permohonan: **Menunggu keputusan Puslapdik**, **Kemendikbudristek**.
