---
title: Penyesuaian UKT Semester Genap 2025/2026
author: registrasi
date: '2025-11-05'
slug: []
categories: 
  - ''
tags:
  - ukt
  - penyesuaian ukt
description: ''
thumbnail: ''
draft: true
---

Universitas Sultan Ageng Tirtayasa kembali mengeluarkan kebijakan penyesuaian UKT untuk periode Semester Genap Tahun Akademik 2025/2026 berdasarkan Peraturan Rektor Universitas Sultan Ageng Tirtayasa Nomor 15 Tahun 2025. Sebelum melakukan pendaftaran penyesuaian UKT, mahasiswa diharapkan mencermati dan memahami ketentuan-ketentuan berikut.

1.  Penyesuaian UKT hanya diberikan kepada mahasiswa program sarjana dan diploma **yang aktif** Angkatan 2024 dan sebelumnya hanya yang mengajukan permohonan.

2.  Penyesuaian UKT yang dapat dimohonkan oleh mahasiswa :

    **a. Perubahan Kelompok UKT Per-semester**; **wajib mengajukan** ulang di setiap semester.

    1)  Perubahan Kelompok UKT bagi Yatim.
    2)  Perubahan Kelompok UKT bagi orang tua (penanggung jawab) terkena PHK.

    **b. Perubahan Kelompok UKT Permanen**; **tidak perlu** mengajukan ulang di setiap semester.

    1.  Orang Tua Sakit Permanen sehingga tidak bisa melaksanakan aktifitas,
    2.  Orang Tua Pensiun.

3.  Penyesuaian UKT Kelompok Yatim dan Yatim Piatu tidak berlaku bagi yang UKT kategori I (Rp. 500.000) dan II (Rp. 1.000.000)

4.  **Mahasiswa jalur MANDIRI dengan UKT kategori 3 tidak bisa mendaftar penyesuaian UKT (karena UKT minimal adalah K3)**.

5.  **Mahasiswa penerima Beasiswa tidak bisa mendaftar penyesuaian UKT.**

6.  SEMUA DOKUMEN PENDUKUNG / SURAT KETERANGAN HARUS DOKUMEN TERBARU **(DITANDATANGANI BULAN NOVEMBER 2025 )**<br><br>

------------------------------------------------------------------------

> Bagi yang kesulitan dalam melakukan pendaftaran, perhatikan hal-hal berikut:
>
> 1.  Pastikan sudah *login* ke [**mail.google.com**](mail.google.com) menggunakan akun email Untirta masing-masing pendaftar
> 2.  Pendaftar **WAJIB** menggunakan akun email Untirta masing-masing (**NIM pendafar diambil dari email yang digunakan**)
> 3.  Jika lupa *password* email Untirta, silakan hubungi [**helpdesk Spada**](http://helpdesk.spada.untirta.ac.id/) **/ Pusdainfo**

------------------------------------------------------------------------

<br><br>

### 1. **Penyesuaian UKT 50%**

Berdasarkan Peraturan Rektor terbaru, Penyesuaian UKT 50% hanya dibuka di semester ganjil. Berikut adalah persyaratan untuk Penyesuaian UKT 50%:

-   Pada semester ganjil, mahasiswa berada pada semester 9 bagi mahasiswa S1 dan semester 7 bagi mahasiswa D3 dan hanya akan mengambil Mata Kuliah **Tugas Akhir/Skripsi** (6 Sks) serta tidak ada mata kuliah lain pada semester ganjil tersebut.
-   Jika pada semester ganjil mahasiswa tidak bisa menyelesaikan sampai sidang skripsi/tugas akhir, maka **UKT akan dikembalikan ke UKT awal di semester berikutnya**.
-   Tidak berlaku bagi kelompok **UKT K1 (Rp500.000,00)** dan **K2 (Rp1.000.000,00)**
-   Tidak berlaku bagi yang UKT Yatim (Yatim Piatu)

### **2. Penyesuaian UKT Kelompok Yatim dan Yatim Piatu**

Penyesuaian UKT Kelompok Yatim dan Yatim Piatu adalah pengurangan UKT yang diberikan kepada mahasiswa dengan golongan UKT minimal 4 di mana orang tua/wali mahasiswa meninggal dunia saat mahasiswa sudah menjadi mahasiswa Untirta sehingga kesulitan membayar UKT.

**Bagi mahasiswa yang sudah mendapatkan penyesuaian UKT Kelompok Yatim dan Yatim Piatu di semester sebelumnya dan tidak memperbaharui data pada semester ini, maka nominal tagihan UKT di semester ini akan kembali ke nominal UKT sebelumnya.**

Berikut adalah berkas-berkas yang harus disiapkan:

1.  KTP Mahasiswa
2.  Kartu Keluarga
3.  Akta Kematian
4.  Surat Pernyataan **Ibu** belum menikah lagi (**terbaru / bulan November 2025**) dengan format yang bisa diunduh [**di sini**](https://drive.google.com/file/d/1-9lDG_d-1xkqbE_MW3lY4xqlwwfaTY5p/view?usp=sharing) (***login*** **menggunakan email Untirta pendaftar**).
5.  SURAT PERNYATAAN KEABSAHAN DATA. Silahkan Format Surat bisa DIUNDUH [**di sini**](https://drive.google.com/file/d/1-J-Dc6o0MCw_JqFKIhjiZUmaXZPMEO7A/view?usp=sharing) (***login*** **menggunakan email Untirta pendaftar**).

Pendaftaran penyesuaian UKT Kelompok Yatim dan Yatim Piatu dilakukan dengan mengisi formulir berikut **menggunakan akun email Untirta pendaftar** dari tanggal **20 - 24 November 2025 pukul 15.00 WIB**.

1.  Sebelum Angkatan 2024 daftar [**di sini**](https://forms.gle/A32hZjyPX3uGzNK26)
2.  Angkatan 2024 daftar [**di sini**](https://forms.cloud.microsoft/r/X0gqNpK6pf)

### **3. Penyesuaian UKT (PHK/Pensiun/Sakit Permanen)**

Penyesuaian UKT ini diberikan kepada mahasiswa di mana Orang Tua / Wali yang terkena PHK, Pensiun, atau Sakit Permanen. Penyesuaian ini paling banyak 2 tingkat dan minimal diajukan oleh **Mahasiswa dengan Kelompok UKT K4** (**kategori sakit permanen** dan **orang tua/wali pensiun**) dan **Kelompok UKT K3** untuk kategori lainnya

Berikut adalah berkas-berkas yang harus diunggah.

a.  SURAT PERNYATAAN KEABSAHAN DATA. Silahkan Format Surat bisa DIUNDUH [**di sini**](https://drive.google.com/file/d/1-J-Dc6o0MCw_JqFKIhjiZUmaXZPMEO7A/view?usp=sharing) (***login*** **menggunakan email Untirta pendaftar**).
b.  KTP Orang Tua / Wali (**format image**)
c.  Persyaratan khusus dalam format PDF (**pilih salah satu**):
    1.  SURAT BUKTI **PHK** dan SURAT KETERANGAN TIDAK BEKERJA bisa DIUNDUH [**di sini**](https://drive.google.com/file/d/1iUVSPyeSSL8dBIg7C7n5Xp3vwE7EMXFV/view?usp=sharing) bagi pendaftar **kategori Orang Tua / Wali mengalami Pemutusan Hubungan Kerja (PHK) - 2 file digabungkan.**

    2.  SURAT KETERANGAN **PENSIUN** dari instansi atau perusahaan (**bukan dari kelurahan**) bagi pendaftar **kategori Orang Tua / Wali sudah Pensiun**

    3.  SURAT KETERANGAN DARI **PIMPINAN RUMAH SAKIT PEMERINTAH** (lengkap dengan Nomor Contact) yang menyatakan bahwa orang tua / wali menderita Sakit Permanen sehingga tidak bisa melaksanakan aktivitas kerja bagi pendaftar **kategori Orang Tua / Wali menderita sakit permanen yang menyebabkan tidak bisa melaksanakan aktifitas bekerja**

        **\*\* Semua Surat Keterangan harus yang terbaru ditandatangani bulan November 2025**

Pendaftaran dapat dilakukan dengan mengisi formulir berikut **menggunakan akun email Untirta pendaftar** dari tanggal **24 - 24 November 2025 pukul 16.00 WIB.**

1.  Sebelum Angkatan 2024 daftar [**di sini**](https://forms.gle/A32hZjyPX3uGzNK26)
2.  Angkatan 2024 daftar [**di sini**](https://forms.cloud.microsoft/r/X0gqNpK6pf)

<br><br>

```{r message=FALSE, warning=FALSE, include=FALSE}
Sys.setlocale("LC_TIME", "IND") 
```

**Helpdesk :**

**Hotline Registrasi** : +6281311734542 **Hotline PNBP** : +6281387220826

Informasi Hasil Verifikasi Penyesuaian UKT oleh Sub. PNBP akan disampaikan melalui email mahasiswa.

<br><br><br>
